export enum SystemMutationTypes {
    SET_SYS_CONFIG = 'SET_SYS_CONFIG',
    SET_MENU = 'SET_MENU',
    SET_ASYNC_ROUTES = 'SET_ASYNC_ROUTES'
  }
  
  export enum SystemActionTypes {
    ACTION_GET_SYS_CONFIG = 'ACTION_GET_SYS_CONFIG',
    ACTION_GET_MENU = 'ACTION_GET_MENU',
    ACTION_SET_ASYNC_ROUTES = 'ACTION_SET_ASYNC_ROUTES'
  }
  